**1. Завантаження та огляд**

In [4]:
import pandas as pd

df = pd.read_csv("tip.csv")
print("Перші 5 рядків:", df.head(5)) # без числа за замовчуванням також виведуться перші 5 рядків.

print("Розмір датасету:", df.shape)

print("Назви всіх колонок:", df.columns)

print("Інформація про типи даних:")
df.info()

Перші 5 рядків:    total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
Розмір датасету: (244, 7)
Назви всіх колонок: Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')
Інформація про типи даних:
<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

---
**2. Базова вибірка даних**

In [3]:
import pandas as pd

df = pd.read_csv("tip.csv")

display(df ["total_bill"])
display(df [["total_bill", "tip"]])
display(df.head(10))
display(df.iloc[5])

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

total_bill     25.29
tip             4.71
sex             Male
smoker            No
day              Sun
time          Dinner
size               4
Name: 5, dtype: object

---
**3. Фільтрація даних**

In [4]:
# Всі рахунки більше 20 доларів:

df[df["total_bill"] > 20]
bill_over_20 = df[df["total_bill"] > 20]
print("Кількість записів:", bill_over_20.shape[0])
display(bill_over_20.head(5))

# Всі відвідувачі-жінки:

fem_vis = df[df["sex"] == "Female"]
print("Всі відвідувачі - жінки:",fem_vis.shape[0])
display(fem_vis.head(5))

# Рахунки на вечерю (`time == 'Dinner'`)

dinner = df[df["time"] == "Dinner"]
print("Кількість записів:", dinner.shape[0])
display(dinner.head(5))

# Рахунки на вечерю з сумою чеку більше 30 доларів.

dinner_over_30 = df[
    (df["time"] == "Dinner") &
    (df["total_bill"] > 30)]
print("Кількість записів:", dinner_over_30.shape[0])
display(dinner_over_30.head(5))

Кількість записів: 97

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
7       26.88  3.12    Male     No  Sun  Dinner     4

Всі відвідувачі - жінки: 87

    total_bill   tip     sex smoker  day    time  size
0        16.99  1.01  Female     No  Sun  Dinner     2
4        24.59  3.61  Female     No  Sun  Dinner     4
11       35.26  5.00  Female     No  Sun  Dinner     4
14       14.83  3.02  Female     No  Sun  Dinner     2
16       10.33  1.67  Female     No  Sun  Dinner     3

Кількість записів: 176

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

Кількість записів: 27

    total_bill   tip     sex smoker  day    time  size
11       35.26  5.00  Female     No  Sun  Dinner     4
23       39.42  7.58    Male     No  Sat  Dinner     4
39       31.27  5.00    Male     No  Sat  Dinner     3
44       30.40  5.60    Male     No  Sun  Dinner     4
47       32.40  6.00    Male     No  Sun  Dinner     4

---
**4. Описова статистика**

In [5]:
average_bill = df["total_bill"].mean()
display(average_bill)

max_tips = df["tip"].max()
display(max_tips)

np.float64(19.78594262295082)

np.float64(10.0)

In [6]:
max_tips = df["tip"].mean()

display(max_tips)

print(df.isnull().sum())

df[df['time'] == "Lunch"]
lunch_count = df[df["time"] == "Lunch"].shape[0]
print("Кількість обідів:", lunch_count)

df[df["time"] == "Dinner"]
dinner_count = df[df["time"] == "Dinner"].shape[0]
print("Кількість вечерь", dinner_count)

np.float64(2.99827868852459)

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64
Кількість обідів: 68
Кількість вечерь 176

---
**5. Статистика із групуванням**

In [11]:
avr_by_sex = df.groupby("sex")["total_bill"].mean()
display(avr_by_sex)
avr_by_day = df.groupby("day")["tip"].mean()
display(avr_by_day)
df["day"].value_counts()

sex
Female    18.056897
Male      20.744076
Name: total_bill, dtype: float64

day
Fri     2.734737
Sat     2.993103
Sun     3.255132
Thur    2.771452
Name: tip, dtype: float64

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

---
**6. Створення нової колонки**

In [13]:
df["tip_percentage"] = (df["tip"] / df["total_bill"]) * 100
display(df.head(10))

   total_bill   tip     sex smoker  day    time  size  tip_percentage
0       16.99  1.01  Female     No  Sun  Dinner     2        5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3       16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3       16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2       13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4       14.680765
5       25.29  4.71    Male     No  Sun  Dinner     4       18.623962
6        8.77  2.00    Male     No  Sun  Dinner     2       22.805017
7       26.88  3.12    Male     No  Sun  Dinner     4       11.607143
8       15.04  1.96    Male     No  Sun  Dinner     2       13.031915
9       14.78  3.23    Male     No  Sun  Dinner     2       21.853857

---
**7. Сортування**

In [17]:
display(df.sort_values("total_bill"))

display(df.sort_values("tip", ascending=False))

display(df.nlargest(5, "tip"))

     total_bill    tip     sex smoker   day    time  size
67         3.07   1.00  Female    Yes   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
172        7.25   5.15    Male    Yes   Sun  Dinner     2
149        7.51   2.00    Male     No  Thur   Lunch     2
..          ...    ...     ...    ...   ...     ...   ...
182       45.35   3.50    Male    Yes   Sun  Dinner     3
156       48.17   5.00    Male     No   Sun  Dinner     6
59        48.27   6.73    Male     No   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
170       50.81  10.00    Male    Yes   Sat  Dinner     3

[244 rows x 7 columns]

     total_bill    tip     sex smoker   day    time  size
170       50.81  10.00    Male    Yes   Sat  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
..          ...    ...     ...    ...   ...     ...   ...
0         16.99   1.01  Female     No   Sun  Dinner     2
111        7.25   1.00  Female     No   Sat  Dinner     1
92         5.75   1.00  Female    Yes   Fri  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1
236       12.60   1.00    Male    Yes   Sat  Dinner     2

[244 rows x 7 columns]

     total_bill    tip   sex smoker   day    time  size
170       50.81  10.00  Male    Yes   Sat  Dinner     3
212       48.33   9.00  Male     No   Sat  Dinner     4
23        39.42   7.58  Male     No   Sat  Dinner     4
59        48.27   6.73  Male     No   Sat  Dinner     4
141       34.30   6.70  Male     No  Thur   Lunch     6